using Titanis;

namespace Atlas.Protocols.Smb.Modules;

internal sealed record AvService(string Name, string Description);
internal sealed record AvPipe(string Pattern, string[] Processes);
internal sealed record AvProduct(string Name, AvService[] Services, AvPipe[] Pipes);

internal static class SmbEnumAvData
{
	public static readonly AvProduct[] Products = new AvProduct[]
	{
		new AvProduct("Acronis Cyber Protect Active Protection", new AvService[] { new AvService("AcronisActiveProtectionService", "Acronis Active Protection Service") }, new AvPipe[] {  }),
		new AvProduct("Avast / AVG", new AvService[] { new AvService("AvastWscReporter", "Avast WSC Reporter Service"), new AvService("aswbIDSAgent", "Avast IDS Agent Service"), new AvService("AVGWscReporter", "AVG WSC Reporter Service"), new AvService("avgbIDSAgent", "AVG IDS Agent Service") }, new AvPipe[] { new AvPipe("aswCallbackPipe*", new string[] { "AvastSvc.exe", "aswEngSrv.exe" }), new AvPipe("avgCallbackPipe*", new string[] { "AVGSvc.exe", "aswEngSrv.exe" }) }),
		new AvProduct("Bitdefender", new AvService[] { new AvService("bdredline_agent", "Bitdefender Agent RedLine Service"), new AvService("BDAuxSrv", "Bitdefender Auxiliary Service"), new AvService("UPDATESRV", "Bitdefender Desktop Update Service"), new AvService("VSSERV", "Bitdefender Virus Shield"), new AvService("bdredline", "Bitdefender RedLine Service"), new AvService("EPRedline", "Bitdefender Endpoint Redline Service"), new AvService("EPUpdateService", "Bitdefender Endpoint Update Service"), new AvService("EPSecurityService", "Bitdefender Endpoint Security Service"), new AvService("EPProtectedService", "Bitdefender Endpoint Protected Service"), new AvService("EPIntegrationService", "Bitdefender Endpoint Integration Service") }, new AvPipe[] { new AvPipe("\\bdConnector\\ServiceControl\\EPSecurityService.exe", new string[] { "EPConsole.exe" }), new AvPipe("etw_sensor_pipe_ppl", new string[] { "EPProtectedService.exe" }), new AvPipe("local\\msgbus\\antitracker.low\\*", new string[] { "bdagent.exe" }), new AvPipe("local\\msgbus\\aspam.actions.low\\*", new string[] { "bdagent.exe" }), new AvPipe("local\\msgbus\\bd.process.broker.pipe", new string[] { "bdagent.exe", "bdservicehost.exe", "updatesrv.exe" }), new AvPipe("local\\msgbus\\bdagent*", new string[] { "bdagent.exe" }), new AvPipe("local\\msgbus\\bdauxsrv", new string[] { "bdagent.exe", "bdntwrk.exe" }) }),
		new AvProduct("Carbon Black App Control", new AvService[] { new AvService("Parity", "Carbon Black App Control Agent") }, new AvPipe[] {  }),
		new AvProduct("Check Point Endpoint Security", new AvService[] { new AvService("CPDA", "Check Point Endpoint Agent"), new AvService("vsmon", "Check Point Endpoint Security Network Protection"), new AvService("CPFileAnlyz", "Check Point Endpoint Security File Analyzer"), new AvService("EPClientUIService", "Check Point Endpoint Security Client UI") }, new AvPipe[] {  }),
		new AvProduct("Cortex", new AvService[] { new AvService("xdrhealth", "Cortex XDR Health Helper"), new AvService("cyserver", "Cortex XDR") }, new AvPipe[] {  }),
		new AvProduct("CrowdStrike", new AvService[] { new AvService("CSFalconService", "CrowdStrike Falcon Sensor Service") }, new AvPipe[] { new AvPipe("CrowdStrike\\{*", new string[] { "CSFalconContainer.exe", "CSFalconService.exe" }) }),
		new AvProduct("Cybereason", new AvService[] { new AvService("CybereasonActiveProbe", "Cybereason Active Probe"), new AvService("CybereasonCRS", "Cybereason Anti-Ransomware"), new AvService("CybereasonBlocki", "Cybereason Execution Prevention") }, new AvPipe[] { new AvPipe("CybereasonAPConsoleMinionHostIpc_*", new string[] { "minionhost.exe" }), new AvPipe("CybereasonAPServerProxyIpc_*", new string[] { "minionhost.exe" }) }),
		new AvProduct("Cynet", new AvService[] { new AvService("CynetLauncher", "CynetLauncher") }, new AvPipe[] {  }),
		new AvProduct("Elastic EDR", new AvService[] { new AvService("Elastic Agent", "Elastic Agent Service"), new AvService("ElasticEndpoint", "Elastic Endpoint Security Service") }, new AvPipe[] { new AvPipe("ElasticEndpointServiceComms-*", new string[] { "elastic-endpoint.exe" }), new AvPipe("elastic-agent-system", new string[] { "elastic-agent.exe" }) }),
		new AvProduct("ESET", new AvService[] { new AvService("ekm", "ESET"), new AvService("epfw", "ESET"), new AvService("epfwlwf", "ESET"), new AvService("epfwwfp", "ESET"), new AvService("EraAgentSvc", "ESET Management Agent service"), new AvService("ERAAgent", "ESET Management Agent service"), new AvService("efwd", "ESET Communication Forwarding Service"), new AvService("ehttpsrv", "ESET HTTP Server") }, new AvPipe[] { new AvPipe("nod_scriptmon_pipe", new string[] { "" }) }),
		new AvProduct("FortiClient", new AvService[] { new AvService("FA_Scheduler", "FortiClient Service Scheduler"), new AvService("FCT_SecSvr", "Forticlient Endpoint Protected Process Service") }, new AvPipe[] { new AvPipe("FortiClient_DBLogDaemon", new string[] { "FCDBLog.exe" }), new AvPipe("FC_*", new string[] { "FortiTray.exe" }) }),
		new AvProduct("FortiEDR", new AvService[] { new AvService("FortiEDR Collector Service", "Host component of the Fortinet Endpoint Detection and Response Platform") }, new AvPipe[] {  }),
		new AvProduct("G DATA Security Client", new AvService[] { new AvService("AVKWCtl", "Anti-virus Kit Window Control"), new AvService("AVKProxy", "G Data AntiVirus Proxy Service"), new AvService("GDScan", "GDSG Data AntiVirus Scan Service") }, new AvPipe[] { new AvPipe("exploitProtectionIPC", new string[] { "AVKWCtlx64.exe" }) }),
		new AvProduct("HarfangLab EDR", new AvService[] { new AvService("hurukai", "HarfangLab Hurukai Agent"), new AvService("Hurukai agent", "HarfangLab Hurukai Agent Service"), new AvService("HarfangLab Hurukai agent", "HarfangLab Hurukai Agent Program"), new AvService("hurukai-av", "HarfangLab Hurukai Antivirus"), new AvService("hurukai-ui", "HarfangLab Hurukai UI") }, new AvPipe[] { new AvPipe("hurukai-control", new string[] { "hurukai.exe" }), new AvPipe("hurukai-servicing", new string[] { "hurukai.exe" }), new AvPipe("hurukai-amsi", new string[] { "hurukai.exe" }) }),
		new AvProduct("Ivanti Security", new AvService[] { new AvService("STAgent$Shavlik Protect", "Ivanti Security Controls Agent"), new AvService("STDispatch$Shavlik Protect", "Ivanti Security Controls Agent Dispatcher") }, new AvPipe[] {  }),
		new AvProduct("Kaseya Agent Endpoint", new AvService[] { new AvService("KAENDKSAASC*", "Virtual System Administrator Endpoint"), new AvService("KAKSAASC*", "Machine.Group ID:*") }, new AvPipe[] { new AvPipe("kaseyaUserKSA*", new string[] { "KaUsrTsk.exe" }), new AvPipe("kaseyaAgentKSA*", new string[] { "AgentMon.exe" }) }),
		new AvProduct("Kaspersky Security for Windows Server", new AvService[] { new AvService("kavfsslp", "Kaspersky Security Exploit Prevention Service"), new AvService("KAVFS", "Kaspersky Security Service"), new AvService("KAVFSGT", "Kaspersky Security Management Service"), new AvService("klnagent", "Kaspersky Security Center") }, new AvPipe[] { new AvPipe("Exploit_Blocker", new string[] { "kavfswh.exe" }) }),
		new AvProduct("Malwarebytes", new AvService[] { new AvService("MBAMService", "Malwarebytes Service"), new AvService("MBEndpointAgent", "Malwarebytes Cloud Endpoint Agent Service") }, new AvPipe[] { new AvPipe("MBLG", new string[] { "MBAMService.exe" }), new AvPipe("MBEA2_R", new string[] { "MBCloudEA.exe" }), new AvPipe("MBEA2_W", new string[] { "MBCloudEA.exe" }) }),
		new AvProduct("Panda Adaptive Defense 360", new AvService[] { new AvService("PandaAetherAgent", "Panda Endpoint Agent"), new AvService("PSUAService", "Panda Product Service"), new AvService("NanoServiceMain", "Panda Cloud Antivirus Service") }, new AvPipe[] { new AvPipe("NNS_API_IPC_SRV_ENDPOINT", new string[] { "PSANHost.exe" }), new AvPipe("PSANMSrvcPpal", new string[] { "PSUAService.exe" }) }),
		new AvProduct("Rapid7", new AvService[] { new AvService("ir_agent", "Rapid7 Insight Agent") }, new AvPipe[] {  }),
		new AvProduct("SentinelOne", new AvService[] { new AvService("SentinelAgent", "SentinelOne Endpoint Protection Agent"), new AvService("SentinelStaticEngine", "Manage static engines for SentinelOne Endpoint Protection"), new AvService("LogProcessorService", "Manage logs for SentinelOne Endpoint Protection") }, new AvPipe[] { new AvPipe("SentinelAgentWorkerCert.*", new string[] { "" }), new AvPipe("DFIScanner.Etw.*", new string[] { "SentinelStaticEngine.exe" }), new AvPipe("DFIScanner.Inline.*", new string[] { "SentinelAgent.exe" }) }),
		new AvProduct("Sophos Intercept X", new AvService[] { new AvService("SntpService", "Sophos Network Threat Protection"), new AvService("Sophos Endpoint Defense Service", "Sophos Endpoint Defense Service"), new AvService("Sophos File Scanner Service", "Sophos File Scanner Service"), new AvService("Sophos Health Service", "Sophos Health Service"), new AvService("Sophos Live Query", "Sophos Live Query"), new AvService("Sophos Managed Threat Response", "Sophos Managed Threat Response"), new AvService("Sophos MCS Agent", "Sophos MCS Agent"), new AvService("Sophos MCS Client", "Sophos MCS Client"), new AvService("Sophos System Protection Service", "Sophos System Protection Service") }, new AvPipe[] { new AvPipe("SophosUI", new string[] { "" }), new AvPipe("SophosEventStore", new string[] { "" }), new AvPipe("sophos_deviceencryption", new string[] { "" }), new AvPipe("sophoslivequery_*", new string[] { "" }) }),
		new AvProduct("Symantec Endpoint Protection", new AvService[] { new AvService("SepMasterService", "Symantec Endpoint Protection"), new AvService("SepScanService", "Symantec Endpoint Protection Scan Services"), new AvService("SNAC", "Symantec Network Access Control") }, new AvPipe[] {  }),
		new AvProduct("Trellix Endpoint Detection and Response (EDR)", new AvService[] { new AvService("McAfee Endpoint Security Platform Service", "Trellix Core Service"), new AvService("mfemactl", "Trellix Management Service"), new AvService("mfemms", "McAfee Management Service"), new AvService("mfefire", "Trellix Firewall Core Service"), new AvService("masvc", "Trellix Agent Service"), new AvService("macmnsvc", "Trellix Agent Common Service"), new AvService("mfetp", "Trellix Endpoint Threat Prevention Service"), new AvService("mfewc", "Trellix Endpoint Security Web Control Service"), new AvService("mfeaack", "Trellix Anti-Malware Core Service") }, new AvPipe[] { new AvPipe("TrellixEDR_Pipe_*", new string[] { "McAfeeEDR.exe" }), new AvPipe("mfemactl_*", new string[] { "mfemactl.exe" }), new AvPipe("mfefire_*", new string[] { "mfefire.exe" }), new AvPipe("McAfeeAgent_Pipe_*", new string[] { "McAfeeAgent.exe" }), new AvPipe("mfetp_*", new string[] { "mfetp.exe" }) }),
		new AvProduct("Trend Micro Endpoint Security", new AvService[] { new AvService("Trend Micro Endpoint Basecamp", "Trend Micro Endpoint Basecamp"), new AvService("TMBMServer", "Trend Micro Unauthorized Change Prevention Service"), new AvService("Trend Micro Web Service Communicator", "Trend Micro Web Service Communicator"), new AvService("TMiACAgentSvc", "Trend Micro Application Control Service (Agent)"), new AvService("CETASvc", "Trend Micro Cloud Endpoint Telemetry Service"), new AvService("iVPAgent", "Trend Micro Vulnerability Protection Service (Agent)"), new AvService("ds_agent", "Trend Micro Deep Security Agent"), new AvService("ds_monitor", "Trend Micro Deep Security Monitor"), new AvService("ds_notifier", "Trend Micro Deep Security Notifier") }, new AvPipe[] { new AvPipe("IPC_XBC_XBC_AGENT_PIPE_*", new string[] { "EndpointBasecamp.exe" }), new AvPipe("iacagent_*", new string[] { "TMiACAgentSvc.exe" }), new AvPipe("OIPC_LWCS_PIPE_*", new string[] { "TmListen.exe" }), new AvPipe("Log_ServerNamePipe", new string[] { "LogServer.exe" }), new AvPipe("OIPC_NTRTSCAN_PIPE_*", new string[] { "Ntrtscan.exe" }) }),
		new AvProduct("Wazuh", new AvService[] { new AvService("WazuhSvc", "Wazuh Windows Agent") }, new AvPipe[] {  }),
		new AvProduct("Windows Defender", new AvService[] { new AvService("WinDefend", "Windows Defender Antivirus Service"), new AvService("Sense", "Windows Defender Advanced Threat Protection Service"), new AvService("WdNisSvc", "Windows Defender Antivirus Network Inspection Service") }, new AvPipe[] {  }),
		new AvProduct("WithSecure Elements", new AvService[] { new AvService("fsdevcon", "WithSecure Device Control"), new AvService("fshoster", "WithSecure Hoster"), new AvService("fsnethoster", "WithSecure Hoster (Restricted)"), new AvService("fsulhoster", "WithSecure Ultralight Hoster"), new AvService("fsulnethoster", "WithSecure Ultralight Network Hoster"), new AvService("fsulprothoster", "WithSecure Ultralight Protected Hoster"), new AvService("wsulavprohoster", "WithSecure Ultralight Protected AV Hoster") }, new AvPipe[] { new AvPipe("FS_CCFIPC_*", new string[] { "fsatpn.exe", "fsatpl.exe", "fshoster32.exe", "fsulprothoster.exe", "fsulprothoster.exe", "fshoster64.exe", "FsPisces.exe", "fsdevcon.exe" }) }),
	};
}
